import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import zhCn from 'element-plus/es/locale/lang/zh-cn'
import 'element-plus/dist/index.css'
import './style.css'
import './layout.css'
import './screen.css'
import './education.css'
import App from './App.vue'
import { createPinia } from 'pinia'
createApp(App).use(createPinia()).use(ElementPlus, { locale: zhCn }).mount('#app')
