import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import './style.css'
import './layout.css'
import './screen.css'
import './education.css'
import App from './App.vue'
import { createPinia } from 'pinia'
createApp(App).use(createPinia()).use(ElementPlus).mount('#app')
